### PR TITLE
Support multiple trackers

### PR DESCRIPTION
**Pull request by doapp-ryanp**
First off THANK YOU for making this library. Saves me tons of time from having to write my own.

This PR adds functionality to support events going to multiple tracker IDs.

A bit unrelated: why do you do the `POST`s synchronously?  We don't care about the response body (or the RC for that matter really) why are they not `POST`ed async?

### CODE REVIEW

**Comment by silentpickle** [comment]
Once the request leaves the function scope, the request is gone forever (garbage collected, if you want to call it that) whether it made it out the door or not.   So the syncronous request holds the function scope until it's completed.

There's a workaround for this in that you can keep the requests in a global array somewhere, and clean the queue periodically (on subsequent requests) of completed requests.

**Comment by doapp-ryanp** [comment]
OK. Yikes. I've only been using BrightScript for a week now so this helps

**Comment by cdthompson** [comment]
@doapp-ryanp Thanks for the pull request!  I have to wonder, what is the driving use case for multiple tracking ids?  Do you really want to send identical events to all tracking ids?

Since I think the typical use case is a single tracking id, can we change the initGAMobile to take either a String or Array as a first argument and then sort it out?  This would also help in keeping it backward compatible for the 3 users we already have ;)

**Comment by doapp-ryanp** [comment]
Hi @cdthompson,

Re: the use case - I work for a mobile app company, and every GA metric we need to send it to our clients tracker and ours.  Sometimes there is more than 2 depending on how our clients and their business units are broken up.

It is actually a very common use case, so much so that its supported out of the box by the official GA mobile SDKs (ex: [Android docs](https://developers.google.com/analytics/devguides/collection/android/v4/advanced#multiple-trackers))

As for the backwards compat - yes I'm totally fine with that.  As I mentioned above I'm a total `brs` noob so I was not sure how to handle both, but I have a guess (using type checking).  Will be a good learning lesson for me - I'll update this PR shortly.

**Comment by doapp-ryanp** [comment]
OK that last commit should do it. I tested both passing in array of tracker ids and a single string as the param to `initGAMobile`

**Pull request merged**
